export const CREATE_EVENT = 'EVENTS_PAGE/ADD/CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'EVENTS_PAGE/ADD/CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'EVENTS_PAGE/ADD/CREATE_EVENT_FAILURE';
