export const ADD_RANK = 'RANKS_PAGE/ADD_RANK';
export const ADD_RANK_SUCCESS = 'RANKS_PAGE/ADD_RANK_SUCCESS';
export const ADD_RANK_FAILURE = 'RANKS_PAGE/ADD_RANK_FAILURE';

export const UPDATE_RANK = 'RANKS_PAGE/UPDATE_RANK';
export const UPDATE_RANK_SUCCESS = 'RANKS_PAGE/UPDATE_RANK_SUCCESS';
export const UPDATE_RANK_FAILURE = 'RANKS_PAGE/UPDATE_RANK_FAILURE';

export const DELETE_RANK = 'RANKS_PAGE/DELETE_RANK';
export const DELETE_RANK_SUCCESS = 'RANKS_PAGE/DELETE_RANK_SUCCESS';
export const DELETE_RANK_FAILURE = 'RANKS_PAGE/DELETE_RANK_FAILURE';
