export const ADD_PERSONNEL = 'PERSONNELS_PAGE/ADD/ADD_PERSONNEL';
export const ADD_PERSONNEL_SUCCESS =
  'PERSONNELS_PAGE/ADD/ADD_PERSONNEL_SUCCESS';
export const ADD_PERSONNEL_FAILURE =
  'PERSONNELS_PAGE/ADD/ADD_PERSONNEL_FAILURE';
export const TOGGLE_ADD_PERSONNEL_SUCCESS_MESSAGE =
  'PERSONNELS_PAGE/ADD/TOGGLE_ADD_PERSONNEL_SUCCESS_MESSAGE';
