export const DELETE_EVENT = 'EVENTS_PAGE/DELETE/DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'EVENTS_PAGE/DELETE/DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'EVENTS_PAGE/DELETE/DELETE_EVENT_FAILURE';
