export const ADD_STATUS = 'STATUSES_PAGE/ADD_STATUS';
export const ADD_STATUS_SUCCESS = 'STATUSES_PAGE/ADD_STATUS_SUCCESS';
export const ADD_STATUS_FAILURE = 'STATUSES_PAGE/ADD_STATUS_FAILURE';

export const UPDATE_STATUS = 'STATUSES_PAGE/UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'STATUSES_PAGE/UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'STATUSES_PAGE/UPDATE_STATUS_FAILURE';

export const DELETE_STATUS = 'STATUSES_PAGE/DELETE_STATUS';
export const DELETE_STATUS_SUCCESS = 'STATUSES_PAGE/DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAILURE = 'STATUSES_PAGE/DELETE_STATUS_FAILURE';
