export const LOG_OUT = 'LOGOUT';
export const LOG_OUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOGOUT_FAILURE';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';

export const LOAD_RANKS = 'LOAD_RANKS';
export const LOAD_RANKS_SUCCESS = 'LOAD_RANKS_SUCCESS';
export const LOAD_RANKS_FAILURE = 'LOAD_RANKS_FAILURE';

export const LOAD_PLATOONS = 'LOAD_PLATOONS';
export const LOAD_PLATOONS_SUCCESS = 'LOAD_PLATOONS_SUCCESS';
export const LOAD_PLATOONS_FAILURE = 'LOAD_PLATOONS_FAILURE';

export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';

export const LOAD_PERSONNELS = 'LOAD_PERSONNELS';
export const LOAD_PERSONNELS_SUCCESS = 'LOAD_PERSONNELS_SUCCESS';
export const LOAD_PERSONNELS_FAILURE = 'LOAD_PERSONNELS_FAILURE';

export const LOAD_POINTS = 'LOAD_POINTS';
export const LOAD_POINTS_SUCCESS = 'LOAD_POINTS_SUCCESS';
export const LOAD_POINTS_FAILURE = 'LOAD_POINTS_FAILURE';

export const LOAD_STATUSES = 'LOAD_STATUSES';
export const LOAD_STATUSES_SUCCESS = 'LOAD_STATUSES_SUCCESS';
export const LOAD_STATUSES_FAILURE = 'LOAD_STATUSES_FAILURE';
