export const ADD_POINT = 'POINTS_PAGE/ADD_POINT';
export const ADD_POINT_SUCCESS = 'POINTS_PAGE/ADD_POINT_SUCCESS';
export const ADD_POINT_FAILURE = 'POINTS_PAGE/ADD_POINT_FAILURE';

export const UPDATE_POINT = 'POINTS_PAGE/UPDATE_POINT';
export const UPDATE_POINT_SUCCESS = 'POINTS_PAGE/UPDATE_POINT_SUCCESS';
export const UPDATE_POINT_FAILURE = 'POINTS_PAGE/UPDATE_POINT_FAILURE';

export const DELETE_POINT = 'POINTS_PAGE/DELETE_POINT';
export const DELETE_POINT_SUCCESS = 'POINTS_PAGE/DELETE_POINT_SUCCESS';
export const DELETE_POINT_FAILURE = 'POINTS_PAGE/DELETE_POINT_FAILURE';
