export const ADD_PLATOON = 'PLATOONS_PAGE/ADD_PLATOON';
export const ADD_PLATOON_SUCCESS = 'PLATOONS_PAGE/ADD_PLATOON_SUCCESS';
export const ADD_PLATOON_FAILURE = 'PLATOONS_PAGE/ADD_PLATOON_FAILURE';

export const UPDATE_PLATOON = 'PLATOONS_PAGE/UPDATE_PLATOON';
export const UPDATE_PLATOON_SUCCESS = 'PLATOONS_PAGE/UPDATE_PLATOON_SUCCESS';
export const UPDATE_PLATOON_FAILURE = 'PLATOONS_PAGE/UPDATE_PLATOON_FAILURE';

export const DELETE_PLATOON = 'PLATOONS_PAGE/DELETE_PLATOON';
export const DELETE_PLATOON_SUCCESS = 'PLATOONS_PAGE/DELETE_PLATOON_SUCCESS';
export const DELETE_PLATOON_FAILURE = 'PLATOONS_PAGE/DELETE_PLATOON_FAILURE';
